linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unconvert
    - misspell
    - gosec
    - revive

linters-settings:
  govet:
    # Check-shadowing option removed
  revive:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
  exclude-dirs:
    - vendor/
  exclude-files:
    - ".*_test.go"

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
